// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHr1s65BJiAqUDyWl0zsmkAYmIrV2F0xQ',
    appId: '1:607221016043:web:6ebfb320ed004c6ec965ae',
    messagingSenderId: '607221016043',
    projectId: 'locally-8589b',
    authDomain: 'locally-8589b.firebaseapp.com',
    storageBucket: 'locally-8589b.appspot.com',
    measurementId: 'G-8WFY6TV0Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrUUCip5MVnQgYgCKmDIdKCf1yHEGwDbE',
    appId: '1:607221016043:android:bdb468f2e5de415fc965ae',
    messagingSenderId: '607221016043',
    projectId: 'locally-8589b',
    storageBucket: 'locally-8589b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp27WDykDq-IQfqbBmlQ8Omh1dABggz3c',
    appId: '1:607221016043:ios:d73bf34156310c5fc965ae',
    messagingSenderId: '607221016043',
    projectId: 'locally-8589b',
    storageBucket: 'locally-8589b.appspot.com',
    iosClientId: '607221016043-q8eh0gsqi2crj774l2bvfvfo52novp10.apps.googleusercontent.com',
    iosBundleId: 'com.example.locally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp27WDykDq-IQfqbBmlQ8Omh1dABggz3c',
    appId: '1:607221016043:ios:d73bf34156310c5fc965ae',
    messagingSenderId: '607221016043',
    projectId: 'locally-8589b',
    storageBucket: 'locally-8589b.appspot.com',
    iosClientId: '607221016043-q8eh0gsqi2crj774l2bvfvfo52novp10.apps.googleusercontent.com',
    iosBundleId: 'com.example.locally',
  );
}
